# serverless.yml
plugins:
  - serverless-offline
  - serverless-dotenv-plugin

service: dank-meme-bot
    
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}

functions:
  app:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
