# serverless.yml
plugins:
  - serverless-offline
  - serverless-dotenv-plugin

service: dank-meme-bot
    
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:DANK_STAGE}
  region: ${env:DANK_AWS_REGION}

functions:

  sync:
    handler: dist/index.sync
    events:
      - sns: dank-meme-sync

  twitter:
    handler: dist/index.twitter
    events:
      - schedule: rate(3 minutes)

  slack:
    handler: dist/index.slack
    events:
      - http: GET /slack

    
